"""Versão 1.2

Revision ID: 138f534536d2
Revises: 
Create Date: 2025-08-20 14:17:00.083879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138f534536d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsavel',
    sa.Column('responsavel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('responsavel_nome', sa.String(length=255), nullable=False),
    sa.Column('responsavel_siap', sa.String(length=255), nullable=True),
    sa.Column('responsavel_cpf', sa.String(length=255), nullable=True),
    sa.Column('responsavel_data_nascimento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('responsavel_id')
    )
    op.create_table('sala',
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('sala_nome', sa.Text(), nullable=False),
    sa.Column('chave_nome', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('sala_id')
    )
    op.create_table('reserva',
    sa.Column('reserva_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.responsavel_id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['sala.sala_id'], ),
    sa.PrimaryKeyConstraint('reserva_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('sala')
    op.drop_table('responsavel')
    # ### end Alembic commands ###
