"""Primeiro Migrate

Revision ID: 513bfcb877f9
Revises: 
Create Date: 2025-08-17 15:47:09.371326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513bfcb877f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsavel',
    sa.Column('responsavel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('responsavel_nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('responsavel_id')
    )
    op.create_table('sala',
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('sala_nome', sa.Text(), nullable=False),
    sa.Column('chave_nome', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('sala_id')
    )
    op.create_table('reserva',
    sa.Column('reserva_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.responsavel_id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['sala.sala_id'], ),
    sa.PrimaryKeyConstraint('reserva_id')
    )
    op.drop_table('teste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teste',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('teste_pkey'))
    )
    op.drop_table('reserva')
    op.drop_table('sala')
    op.drop_table('responsavel')
    # ### end Alembic commands ###
