"""Modificacao na Tabela Responsavel, SIAP e CPF agora sao unicos.

Revision ID: 6c6d383bcd36
Revises: cbf90009ee3b
Create Date: 2025-09-03 10:01:36.887859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6d383bcd36'
down_revision = 'cbf90009ee3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['responsavel_siap'])
        batch_op.create_unique_constraint(None, ['responsavel_cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
