"""Criação das tabelas finalizacoes e historico

Revision ID: cbf90009ee3b
Revises: 138f534536d2
Create Date: 2025-08-21 09:35:08.965961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf90009ee3b'
down_revision = '138f534536d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico',
    sa.Column('historico_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('historico_id')
    )
    op.create_table('finalizacao',
    sa.Column('finalizacao_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_finalizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.reserva_id'], ),
    sa.PrimaryKeyConstraint('finalizacao_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finalizacao')
    op.drop_table('historico')
    # ### end Alembic commands ###
